/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9.1 */

#ifndef PB_SENSOR_READINGS_PB_H_INCLUDED
#define PB_SENSOR_READINGS_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Enum definitions */
typedef enum _ReadingType {
    ReadingType_NOTUSED = 0,
    ReadingType_TEMP = 1,
    ReadingType_REL_HUMID = 2,
    ReadingType_LIGHT = 3,
    ReadingType_PH = 4,
    ReadingType_EC = 5
} ReadingType;

/* Struct definitions */
typedef struct _Reading {
    ReadingType type;
    float value;
} Reading;

typedef struct _ReadingSlug {
    bool has_power;
    bool has_r1;
    Reading r1;
    bool has_r2;
    Reading r2;
    bool has_r3;
    Reading r3;
} ReadingSlug;


#ifdef __cplusplus
extern "C" {
#endif

/* Helper constants for enums */
#define _ReadingType_MIN ReadingType_NOTUSED
#define _ReadingType_MAX ReadingType_EC
#define _ReadingType_ARRAYSIZE ((ReadingType)(ReadingType_EC+1))

#define Reading_type_ENUMTYPE ReadingType



/* Initializer values for message structs */
#define Reading_init_default                     {_ReadingType_MIN, 0}
#define ReadingSlug_init_default                 {0, false, Reading_init_default, false, Reading_init_default, false, Reading_init_default}
#define Reading_init_zero                        {_ReadingType_MIN, 0}
#define ReadingSlug_init_zero                    {0, false, Reading_init_zero, false, Reading_init_zero, false, Reading_init_zero}

/* Field tags (for use in manual encoding/decoding) */
#define Reading_type_tag                         1
#define Reading_value_tag                        2
#define ReadingSlug_has_power_tag                1
#define ReadingSlug_r1_tag                       2
#define ReadingSlug_r2_tag                       3
#define ReadingSlug_r3_tag                       4

/* Struct field encoding specification for nanopb */
#define Reading_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UENUM,    type,              1) \
X(a, STATIC,   SINGULAR, FLOAT,    value,             2)
#define Reading_CALLBACK NULL
#define Reading_DEFAULT NULL

#define ReadingSlug_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, BOOL,     has_power,         1) \
X(a, STATIC,   OPTIONAL, MESSAGE,  r1,                2) \
X(a, STATIC,   OPTIONAL, MESSAGE,  r2,                3) \
X(a, STATIC,   OPTIONAL, MESSAGE,  r3,                4)
#define ReadingSlug_CALLBACK NULL
#define ReadingSlug_DEFAULT NULL
#define ReadingSlug_r1_MSGTYPE Reading
#define ReadingSlug_r2_MSGTYPE Reading
#define ReadingSlug_r3_MSGTYPE Reading

extern const pb_msgdesc_t Reading_msg;
extern const pb_msgdesc_t ReadingSlug_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define Reading_fields &Reading_msg
#define ReadingSlug_fields &ReadingSlug_msg

/* Maximum encoded size of messages (where known) */
#define ReadingSlug_size                         29
#define Reading_size                             7
#define SENSOR_READINGS_PB_H_MAX_SIZE            ReadingSlug_size

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
